### PR TITLE
Some fixes to be used in scrollable list item

### PR DESCRIPTION
**Pull request by sngo25**
- [x] Restrict drag direction to x axis
- [x] Display swipe wrapper element as block

### CODE REVIEW

**Comment by thomas-hilaire** [comment]
- Do not name PRs and commits on external repo as "INBOX-XX", create a ticket on our own jira which has a reference on this Github PR
- Why a "fix linters" commit ? Do the linters was broken before your PR ?
- Can you change the commit title to give the real reason of "Display swipe wrapper element as block" ? Like "Display as block to ..."

**Comment by sngo25** [comment]
Hi @thomas-hilaire,

> Do not name PRs and commits on external repo as "INBOX-XX", create a ticket on our own jira which has a reference on this Github PR

Agreed.

> Why a "fix linters" commit ? Do the linters was broken before your PR ?

Yes

> Can you change the commit title to give the real reason of "Display swipe wrapper element as block" ? Like "Display as block to ..."

OK, `Display as block to make it work`?

**Comment by thomas-hilaire** [comment]
`Display as block to make it work`, please it was a real remark. 
So it was not working at all before that change ? So what about `Display block wasn't allowing to swipe` ?

**Comment by sngo25** [comment]
@thomas-hilaire the PR is updated, can you validate it?

**Comment by fvn-linagora** [comment]
- I also don't see the point of the "linters" commit from the PR perspective.
- Both remaining commits could be easily merged into a single one before being merged into master, IMHO.

**Comment by sngo25** [comment]
> I also don't see the point of the "linters" commit from the PR perspective.

Actually, the linters were broken before but not during the PR.

> Both remaining commits could be easily merged into a single one before being merged into master, IMHO.

I think 1 commit for each purpose is acceptable, unless you always want to have 1 commit for each PR.

**Comment by ddolcimascolo** [comment]
:+1:

**Pull request merged**
